Repository BrassAmber-Mods/Brass_Amber_BattleTowers, pull requests merged in 2021-12, with the labels that each got.

#36 Update Readme
  README.md
Labels: documentation

#38 Merge Golem-dev into main
  build.gradle
  src/main/java/com/BrassAmber/ba_bt/entity/ai/goal/GolemFireballAttackGoal.java
  src/main/java/com/BrassAmber/ba_bt/entity/ai/target/TargetTaskGolemLand.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/renderer/golem/BTAbstractGolemRenderer.java
  src/main/java/com/BrassAmber/ba_bt/entity/hostile/golem/BTGolemEntityAbstract.java
Labels: bug

#47 Change version to reflect addition of French Translation and Spawner Render fix
  build.gradle
Labels: documentation

#50 Explosion sound volume reduction and general timing/amount cleanup. Spawn golem sound subtitle fixed
  src/main/java/com/BrassAmber/ba_bt/entity/DestroyTowerEntity.java
  src/main/java/com/BrassAmber/ba_bt/entity/ExplosionPhysicsEntity.java
  src/main/resources/assets/ba_bt/lang/en_us.json
Labels: bug, documentation, enhancement
