Repository BrassAmber-Mods/Brass_Amber_BattleTowers, pull requests merged in 2021-11, with the labels that each got.

#22 Skeleton and tab icon
  src/main/java/com/BrassAmber/ba_bt/BTItemGroup.java
  src/main/java/com/BrassAmber/ba_bt/BrassAmberBattleTowers.java
  src/main/java/com/BrassAmber/ba_bt/block/BTBlocks.java
  src/main/java/com/BrassAmber/ba_bt/block/block/TabIconBlock.java
  src/main/java/com/BrassAmber/ba_bt/entity/BTEntityTypes.java
  src/main/java/com/BrassAmber/ba_bt/entity/ai/goal/DualMeleeAttackGoal.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/BTEntityRender.java
  src/main/java/com/BrassAmber/ba_bt/entity/hostile/SilverSkeletonEntity.java
  src/main/java/com/BrassAmber/ba_bt/item/BTItems.java
  src/main/resources/BrassAmberBattleTowers.png
  src/main/resources/META-INF/mods.toml
  src/main/resources/assets/ba_bt/blockstates/silver_block.json
  src/main/resources/assets/ba_bt/blockstates/silver_tiles.json
  src/main/resources/assets/ba_bt/blockstates/tab_icon.json
  src/main/resources/assets/ba_bt/lang/en_us.json
  src/main/resources/assets/ba_bt/models/block/silver_block.json
  src/main/resources/assets/ba_bt/models/block/silver_tiles.json
  src/main/resources/assets/ba_bt/models/block/tab_icon.json
  src/main/resources/assets/ba_bt/models/item/silver_block.json
  src/main/resources/assets/ba_bt/models/item/silver_skeleton_spawn_egg.json
  src/main/resources/assets/ba_bt/models/item/silver_tiles.json
  src/main/resources/assets/ba_bt/models/item/tab_icon.json
  src/main/resources/assets/ba_bt/textures/block/silver/silver_block.png
  src/main/resources/assets/ba_bt/textures/block/silver/silver_tiles.png
  src/main/resources/assets/ba_bt/textures/item/tab_icon.png
  src/main/resources/data/ba_bt/loot_tables/blocks/silver_block.json
  src/main/resources/data/ba_bt/loot_tables/blocks/silver_tiles.json
  src/main/resources/data/ba_bt/recipes/silver_block.json
  src/main/resources/data/ba_bt/recipes/silver_ingot_from_block.json
  src/main/resources/data/ba_bt/recipes/silver_tiles.json
  src/main/resources/data/ba_bt/tags/blocks/silver_blocks.json
  src/main/resources/data/minecraft/tags/blocks/beacon_base_blocks.json
  src/main/resources/data/minecraft/tags/items/beacon_payment_items.json
Labels: enhancement

#25 Update Golem Notes.txt
  Golem Notes.txt
Labels: bug, duplicate, enhancement

#26 Merge "Merge golem fix" into Main
  src/main/java/com/BrassAmber/ba_bt/BTItemGroup.java
  src/main/java/com/BrassAmber/ba_bt/entity/BTEntityTypes.java
  src/main/java/com/BrassAmber/ba_bt/entity/block/MonolithEntity.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/model/block/MonolithModel.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/model/hostile/LandGolemModel.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/model/hostile/OceanGolemModel.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/model/hostile/SkyGolemModel.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/model/hostile/SkyMinionModel.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/renderer/SkyMinionRenderer.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/renderer/block/MonolithRendererAbstract.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/renderer/golem/CoreGolemRenderer.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/renderer/golem/EndGolemRenderer.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/renderer/golem/LandGolemRenderer.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/renderer/golem/NetherGolemRenderer.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/renderer/golem/OceanGolemRenderer.java
  src/main/java/com/BrassAmber/ba_bt/entity/client/renderer/golem/SkyGolemRenderer.java
  src/main/java/com/BrassAmber/ba_bt/entity/hostile/SilverSkeletonEntity.java
  src/main/java/com/BrassAmber/ba_bt/entity/hostile/golem/BTGolemEntityAbstract.java
  src/main/java/com/BrassAmber/ba_bt/entity/hostile/golem/SkyGolemEntity.java
  src/main/java/com/BrassAmber/ba_bt/item/BTItems.java
  src/main/java/com/BrassAmber/ba_bt/item/item/MonolithItem.java
  src/main/resources/assets/ba_bt/lang/en_us.json
  src/main/resources/assets/ba_bt/models/item/monolith_core.json
  src/main/resources/assets/ba_bt/models/item/monolith_end.json
  src/main/resources/assets/ba_bt/models/item/monolith_land.json
  src/main/resources/assets/ba_bt/models/item/monolith_nether.json
  src/main/resources/assets/ba_bt/models/item/monolith_ocean.json
  src/main/resources/assets/ba_bt/models/item/monolith_sky.json
  src/main/resources/assets/ba_bt/models/item/monolith_template.json
  src/main/resources/assets/ba_bt/textures/item/monolith.png
  src/main/resources/assets/ba_bt/textures/item/monolith.png.mcmeta
Labels: duplicate, enhancement

#27 Item texture update
  src/main/resources/assets/ba_bt/textures/block/silver/silver_tiles.png
  src/main/resources/assets/ba_bt/textures/item/guardian_eye/guardian_eye_nether.png
  src/main/resources/assets/ba_bt/textures/item/monolith_key/core_monolith_key.png.mcmeta
  src/main/resources/assets/ba_bt/textures/item/monolith_key/end_monolith_key.png
  src/main/resources/assets/ba_bt/textures/item/monolith_key/end_monolith_key.png.mcmeta
  src/main/resources/assets/ba_bt/textures/item/monolith_key/nether_monolith_key.png
  src/main/resources/assets/ba_bt/textures/item/monolith_key/sky_monolith_key.png.mcmeta
  src/main/resources/assets/ba_bt/textures/item/silver/silver_ingot.png
  src/main/resources/assets/ba_bt/textures/item/silver/silver_shard.png
Labels: enhancement
